package com.supets.pet.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.supets.pet.dao.EmojiHtml;

import com.supets.pet.dao.EmojiHtmlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emojiHtmlDaoConfig;

    private final EmojiHtmlDao emojiHtmlDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emojiHtmlDaoConfig = daoConfigMap.get(EmojiHtmlDao.class).clone();
        emojiHtmlDaoConfig.initIdentityScope(type);

        emojiHtmlDao = new EmojiHtmlDao(emojiHtmlDaoConfig, this);

        registerDao(EmojiHtml.class, emojiHtmlDao);
    }
    
    public void clear() {
        emojiHtmlDaoConfig.getIdentityScope().clear();
    }

    public EmojiHtmlDao getEmojiHtmlDao() {
        return emojiHtmlDao;
    }

}
