package com.supets.pet.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EMOJI_HTML.
 */
public class EmojiHtml {

    private Long id;
    /** Not-null value. */
    private String unified;
    /** Not-null value. */
    private String html;

    public EmojiHtml() {
    }

    public EmojiHtml(Long id) {
        this.id = id;
    }

    public EmojiHtml(Long id, String unified, String html) {
        this.id = id;
        this.unified = unified;
        this.html = html;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUnified() {
        return unified;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUnified(String unified) {
        this.unified = unified;
    }

    /** Not-null value. */
    public String getHtml() {
        return html;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHtml(String html) {
        this.html = html;
    }

}
